package sergisa.drawer;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;
import sergisa.drawer.ui.TitleLabel;

import javax.swing.*;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;
import javax.swing.plaf.FontUIResource;
import javax.swing.text.StyleContext;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.HashMap;
import java.util.Locale;
import java.util.Map;
import java.util.prefs.Preferences;

public class SettingsForm extends JFrame implements ActionListener, ChangeListener {
    private JPanel root;
    private JCheckBox gridShowCheckBox;
    private JCheckBox cursorShowCheckBox;
    private JSpinner gridStepSpinner;
    private TitleLabel titleLabel1;
    private TitleLabel titleLabel2;
    private JButton saveButton;
    private JCheckBox syncUICheckbox;
    Map<JComponent, String> settingControlsMap = new HashMap<>();
    SpinnerNumberModel gridStepSpinnerModel;

    public SettingsForm() {
        gridStepSpinnerModel = new SpinnerNumberModel(0, 0, 50, 1);
        $$$setupUI$$$();
        setSize(500, 500);
        setVisible(true);
        setLocationRelativeTo(null);
        setTitle("Settings");
        setContentPane(root);
        settingControlsMap.put(gridShowCheckBox, "grid.show");
        settingControlsMap.put(cursorShowCheckBox, "crosshair.show");
        settingControlsMap.put(gridStepSpinner, "grid.step");

        updateSettingsGUI();
        syncUICheckbox.addActionListener(e -> {
            toggleListeners(((JCheckBox) e.getSource()).isSelected());
            updateSettingsStorage();
        });
        saveButton.addActionListener(e -> {
            updateSettingsStorage();
            setVisible(false);
            dispose();
        });
    }

    public void updateSettingsStorage() {
        settingControlsMap.forEach((jComponent, paramString) -> {
            setSetting(jComponent);
        });
    }

    private void updateSettingsGUI() {
        for (JComponent control : settingControlsMap.keySet()) {
            if (control instanceof JCheckBox) {
                ((JCheckBox) control).setSelected(Preferences.userRoot().getBoolean(settingControlsMap.get(control), false));
            } else if (control instanceof JSpinner) {
                ((JSpinner) control).setValue(Preferences.userRoot().getInt(settingControlsMap.get(control), 10));
            }
        }
    }

    private void createUIComponents() {
        titleLabel1 = new TitleLabel("wef", SwingConstants.CENTER);
        titleLabel2 = new TitleLabel("wef", SwingConstants.CENTER);
        gridStepSpinner = new JSpinner(gridStepSpinnerModel);
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
        root = new JPanel();
        root.setLayout(new GridLayoutManager(8, 3, new Insets(8, 8, 8, 8), -1, -1));
        final Spacer spacer1 = new Spacer();
        root.add(spacer1, new GridConstraints(6, 0, 1, 3, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1, GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        root.add(gridStepSpinner, new GridConstraints(3, 2, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label1 = new JLabel();
        label1.setText("Шаг сетки");
        root.add(label1, new GridConstraints(3, 0, 1, 2, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 2, false));
        cursorShowCheckBox = new JCheckBox();
        cursorShowCheckBox.setText("Показывать курсор");
        root.add(cursorShowCheckBox, new GridConstraints(2, 0, 1, 3, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 2, false));
        gridShowCheckBox = new JCheckBox();
        gridShowCheckBox.setText("Показывать сетку");
        root.add(gridShowCheckBox, new GridConstraints(1, 0, 1, 3, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 2, false));
        final Spacer spacer2 = new Spacer();
        root.add(spacer2, new GridConstraints(4, 0, 1, 3, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, 1, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(-1, 20), null, 0, false));
        Font titleLabel1Font = this.$$$getFont$$$(null, Font.BOLD, -1, titleLabel1.getFont());
        if (titleLabel1Font != null) titleLabel1.setFont(titleLabel1Font);
        titleLabel1.setHorizontalAlignment(2);
        titleLabel1.setHorizontalTextPosition(2);
        titleLabel1.setText("Настройки графики");
        root.add(titleLabel1, new GridConstraints(5, 0, 1, 3, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        Font titleLabel2Font = this.$$$getFont$$$(null, Font.BOLD, -1, titleLabel2.getFont());
        if (titleLabel2Font != null) titleLabel2.setFont(titleLabel2Font);
        titleLabel2.setHorizontalAlignment(2);
        titleLabel2.setHorizontalTextPosition(2);
        titleLabel2.setText("Настройки сетки");
        root.add(titleLabel2, new GridConstraints(0, 0, 1, 3, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        saveButton = new JButton();
        saveButton.setText("Сохранить");
        root.add(saveButton, new GridConstraints(7, 1, 1, 2, GridConstraints.ANCHOR_EAST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 1, false));
        syncUICheckbox = new JCheckBox();
        syncUICheckbox.setText("Моментально применять");
        root.add(syncUICheckbox, new GridConstraints(7, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    private Font $$$getFont$$$(String fontName, int style, int size, Font currentFont) {
        if (currentFont == null) return null;
        String resultName;
        if (fontName == null) {
            resultName = currentFont.getName();
        } else {
            Font testFont = new Font(fontName, Font.PLAIN, 10);
            if (testFont.canDisplay('a') && testFont.canDisplay('1')) {
                resultName = fontName;
            } else {
                resultName = currentFont.getName();
            }
        }
        Font font = new Font(resultName, style >= 0 ? style : currentFont.getStyle(), size >= 0 ? size : currentFont.getSize());
        boolean isMac = System.getProperty("os.name", "").toLowerCase(Locale.ENGLISH).startsWith("mac");
        Font fontWithFallback = isMac ? new Font(font.getFamily(), font.getStyle(), font.getSize()) : new StyleContext().getFont(font.getFamily(), font.getStyle(), font.getSize());
        return fontWithFallback instanceof FontUIResource ? fontWithFallback : new FontUIResource(fontWithFallback);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return root;
    }

    private void setListeners(JComponent controlUIElement) {
        if (controlUIElement instanceof JCheckBox) {
            ((JCheckBox) controlUIElement).addActionListener(this);
        } else if (controlUIElement instanceof JSpinner) {
            ((JSpinner) controlUIElement).addChangeListener(this);
        }
    }

    private void removeListeners(JComponent controlUIElemnt) {
        if (controlUIElemnt instanceof JCheckBox) {
            ((JCheckBox) controlUIElemnt).removeActionListener(this);
        } else if (controlUIElemnt instanceof JSpinner) {
            ((JSpinner) controlUIElemnt).removeChangeListener(this);
        }
    }

    private void toggleListeners(boolean state) {
        for (JComponent listeningComponent : settingControlsMap.keySet()) {
            if (state) setListeners(listeningComponent);
            else removeListeners(listeningComponent);
        }
    }

    private void setSetting(JComponent controlUIElement) {
        if (controlUIElement instanceof JCheckBox changedCheckbox) {
            Preferences.userRoot().putBoolean(
                    settingControlsMap.get(changedCheckbox),
                    changedCheckbox.isSelected()
            );
        } else if (controlUIElement instanceof JSpinner changedSpinner) {
            Preferences.userRoot().putInt(
                    settingControlsMap.get(changedSpinner),
                    (int) gridStepSpinnerModel.getNumber()
            );
        }
    }

    @Override
    public void actionPerformed(ActionEvent e) {
        JCheckBox changedCheckbox = (JCheckBox) e.getSource();
        setSetting(changedCheckbox);
    }

    @Override
    public void stateChanged(ChangeEvent e) {
        JSpinner changedSpinner = (JSpinner) e.getSource();
        setSetting(changedSpinner);
    }
}
